### ISSUE TITLE
Need to remove or hide the FloatingButton 

### ISSUE THREAD

**Issue by JananniM** [jjochen/JJFloatingActionButton#135]
I have to hide the floating button if the user dont what to show them in once use case.
I am using the object.removeFromSuperview().
When i call again to show the floating Button object is not showing properly.

**Comment by jjochen** [comment]
What do you call when you want to show the floating button again?

The floating button behaves (more or less) like any other view. If you remove it from its superview and want to show it again, you have to add it again and redefine its position. 

I would probably use `object.isHidden = true`.  Like this you can set it to `false` later on.

When you hide the floating button you should probably make sure, it's closed. Otherwise the overlay view and action items are still visible.

**Comment by jjochen** [comment]
I hope this is resolved.
